apiVersion: skaffold/v2beta10
kind: Config

# Standard build used by both "dev" and "run" profiles below
build:

  local:
    tryImportMissing: false
    push: true
    useBuildkit: true
    concurrency: 2
  tagPolicy:
    sha256: {}

  artifacts:
    - image: sample-java-busybox
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
        - './java-project/*'

# Definitions of the "dev" and "run" profiles
profiles:

  # DEV Profile
  # Used when developping. 
  # We will just be using the standard build above without changes
  - name: dev
    deploy:
      helm:
        releases:
          - name: databusybox
            chartPath: helm
            namespace: default
            artifactOverrides:
              skaffold:
                image: sample-java-busybox
            setValues:
              skaffold:
                enabled: true
              tableName: "SQLUser.BusyBoxTable"
              frequency: "10"
              # jdbcConnectionString: "jdbc:IRIS://sds-cp.sds-cp:1972/USER"
              # irisPassword: SYS
              # irisUserName: SuperUser
              jdbcConnectionString: "jdbc:IRIS://isc-iris-db.isc-iris-db:1972/USER"
              irisPassword: test
              irisUserName: SuperUser
